"""Test 2

Revision ID: 3f670eaf2673
Revises: a3d4c429efb9
Create Date: 2022-08-21 11:53:54.031582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f670eaf2673'
down_revision = 'a3d4c429efb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
