"""Test 4

Revision ID: 9cbd7350a619
Revises: cd613a0cd68a
Create Date: 2022-08-21 13:29:19.778887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9cbd7350a619'
down_revision = 'cd613a0cd68a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'is_confirmed')
    op.drop_column('authors', 'is_processed')
    op.drop_column('authors', 'updated_at')
    op.drop_column('authors', 'created_at')
    op.drop_column('authors', 'its_confirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('its_confirmed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('authors', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('authors', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('authors', sa.Column('is_processed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('authors', sa.Column('is_confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
