"""Test

Revision ID: a3d4c429efb9
Revises: 
Create Date: 2022-08-21 09:45:31.091286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d4c429efb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('middle_name', sa.String(length=64), nullable=True))
    op.add_column('authors', sa.Column('is_confirmed', sa.Boolean(), nullable=True))
    op.add_column('authors', sa.Column('is_processed', sa.Boolean(), nullable=True))
    op.add_column('authors', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('authors', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'authors', ['id'])
    op.create_unique_constraint(None, 'books', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_constraint(None, 'authors', type_='unique')
    op.drop_column('authors', 'updated_at')
    op.drop_column('authors', 'created_at')
    op.drop_column('authors', 'is_processed')
    op.drop_column('authors', 'is_confirmed')
    op.drop_column('authors', 'middle_name')
    # ### end Alembic commands ###
