"""Test 3

Revision ID: cd613a0cd68a
Revises: 3f670eaf2673
Create Date: 2022-08-21 11:54:48.544009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd613a0cd68a'
down_revision = '3f670eaf2673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('its_confirmed', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'its_confirmed')
    # ### end Alembic commands ###
