version: '3.8'

services:
  books:
    build:
      context: ./apps/service-books/
      dockerfile: Dockerfile
    image: shelfbook-books
    container_name: shelfbook-books
    working_dir: /app/
    volumes:
      - ./apps/service-books/:/app/
    ports:
      - "8000:8000"
    depends_on:
      - books-db
    restart: always

  books-db:
    image: postgres:13.4
    container_name: shelfbook-books-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=books-db